apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: 1
  selector:
    matchLabels:
      app: aplicacao-todolist
  template:
    metadata: 
      labels:
        app: aplicacao-todolist
    spec:
      containers:
        - name: todolist
          image: andreibr/todolist:1.1
          ports:
          - containerPort: 4000
            name: glowroot
          - containerPort: 8080
            name: app
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            successThreshold: 1
