apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao
spec:
  type: NodePort
  ports: 
    - name: glowroot
      protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30001
    - name: tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: aplicacao-todolist
