version: '3.7'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root 
      - MYSQL_DATABASE=db_todolist
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

  todolist:
    image: teste/todolist:1.0
    networks:
      - backend
    ports:
      - 4000:4000
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - monitoring/grafana.config
    networks:
      - backend
      - frontend
    ports:
      - 3000:3000
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  prometheus:
    image: basi/prometheus-swarm
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
      - prometheus_data:/var/lib/prometheus
    networks:
      - backend
    ports:
      - 9090:9090
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

networks:
  backend:
  frontend:

volumes:
  prometheus_data:
  grafana_data:
  db_data:

