version: '3.7'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root 
      - MYSQL_DATABASE=db_todolist
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

  todolist:
    image: andreibr/todo-list:2.0.2
    networks:
      - backend
    ports:
      - 4000:4000
      - 8080:25000
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

networks:
  backend:

volumes:
  db_data:

