version: '3.7'
services:
  mariadb:
    image: mariadb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=root 
      - MYSQL_DATABASE=db_todolist
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr

  todolist:
    image: andreibr/todolist:1.0
    networks:
      - backend
    ports:
      - 4000:4000
      - 8080:8080
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip

networks:
  backend:

volumes:
  db_data:

