apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-v{{ .Values.service.version }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.container.port }}
    protocol: TCP
    targetPort: {{ .Values.container.port }}
  selector:
    app: {{ .Values.container.name }}
    version: v{{ .Chart.AppVersion }}
  type: {{ .Values.service.type }}
