apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: ExternalName
  externalName: "mydbinstance.cnkc8za0e9tr.us-east-1.rds.amazonaws.com"
  ports:
    - port: 3306
  selector:
    name: mariadb
