apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: statefulset-mariadb
spec:
  serviceName: mariadb
  template:
    metadata:
      labels:
        name: mariadb
    spec:
      containers:
        - name: container-mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: "db_todolist"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "1"
          volumeMounts:
            - name: volume-mariadb
              mountPath: /var/lib/mysql
      volumes:
        - name: volume-mariadb
          persistentVolumeClaim:
            claimName: configuracao-mariadb


