global:
  scrape_interval:     5s
  evaluation_interval: 5s
  external_labels:
      monitor: 'monitoring'

scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['todolist:8080']
    params:
      format: [prometheus]

